dotfiles_dir = ".dotfiles"

[settings]
vars = ["vars.toml"]

[settings.dots]
wezterm = { source = "terminal/wezterm", target = ".config/wezterm" }
fzf = { source = "terminal/fzf", target = ".config/fzf" }
zsh = { source = "terminal/zsh/zshrc", target = ".zshrc" }
starship = { source = "terminal/starship.toml", target = ".config/starship.toml" }
neovim = { source = "nvim", target = ".config/nvim" }
git = { source = "git/gitconfig", target = ".gitconfig" }
dms = { source = "dms/settings.json", target = ".config/DankMaterialShell/settings.json" }
