dotfiles_dir = ".dotfiles"

[settings]
vars = ["vars.toml"]

[settings.dots]
wezterm = { source = "configs/terminal/wezterm", target = ".config/wezterm" }
fzf = { source = "configs/terminal/fzf", target = ".config/fzf" }
zsh = { source = "configs/terminal/zsh/zshrc", target = ".zshrc" }
starship = { source = "configs/terminal/starship.toml", target = ".config/starship.toml" }
neovim = { source = "configs/nvim", target = ".config/nvim" }
git = { source = "configs/git/.gitconfig", target = ".gitconfig" }
dms = { source = "configs/dms/settings.json", target = ".config/DankMaterialShell/settings.json" }
